/*
    1. Llama a los perritos qque estan disponibles para adopcion
*/

CREATE OR REPLACE FUNCTION FIDE_OBTENER_PERRO_DISPONIBLES_FN
RETURN SYS_REFCURSOR
IS
    V_CURSOR_PERRITOS SYS_REFCURSOR;
BEGIN
    OPEN V_CURSOR_PERRITOS FOR
        SELECT  P.ID_PERRITO,
                P.NOMBRE AS NOMBRE_PERRITO,
                P.EDAD,
                P.PESO,
                R.NOMBRE AS RAZA,
                S.NOMBRE AS SEXO
        FROM FIDE_PERRITO_TB P
        JOIN FIDE_RAZA_TB R ON P.ID_RAZA = R.ID_RAZA
        JOIN FIDE_SEXO_TB S ON P.ID_SEXO = S.ID_SEXO
        WHERE P.ID_ESTADO = 1;
    RETURN V_CURSOR_PERRITOS;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO DATOS CON EL ID INDICADO');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR' || SQLERRM);
END FIDE_OBTENER_PERRO_DISPONIBLES_FN;


/*
    2. Busca al perrito y muestra su historial medico
*/
CREATE OR REPLACE FUNCTION FIDE_HISTORIAL_MEDICO_PERRITO_FN (
    P_ID_PERRITO IN FIDE_PERRITO_TB.ID_PERRITO%TYPE)
RETURN VARCHAR2
IS
    CURSOR C_HISTORIAL IS
        SELECT TE.NOMBRE AS TIPO, EP.FECHA_EVENTO, EP.DETALLE
        FROM FIDE_EVENTO_PERRITO_TB EP
        JOIN FIDE_TIPO_EVENTO_TB TE ON EP.ID_TIPO_EVENTO = TE.ID_TIPO_EVENTO
        WHERE EP.ID_PERRITO = P_ID_PERRITO
        AND EP.ID_ESTADO = 1
        ORDER BY EP.FECHA_EVENTO DESC;

    V_HISTORIAL_COMPLETO VARCHAR2(4000) := '';
    V_REGISTRO C_HISTORIAL%ROWTYPE;
BEGIN
    OPEN C_HISTORIAL;
    LOOP
        FETCH C_HISTORIAL INTO V_REGISTRO;
        EXIT WHEN C_HISTORIAL%NOTFOUND;
        V_HISTORIAL_COMPLETO := V_HISTORIAL_COMPLETO || 
                                TO_CHAR(V_REGISTRO.FECHA_EVENTO, 'DD/MM/YYYY') || ' - ' || 
                                V_REGISTRO.TIPO || ': ' || 
                                V_REGISTRO.DETALLE || ' | ';
    END LOOP;
    CLOSE C_HISTORIAL;

    IF V_HISTORIAL_COMPLETO IS NULL OR V_HISTORIAL_COMPLETO = '' THEN
        RETURN 'Sin historial médico registrado.';
    END IF;

    RETURN V_HISTORIAL_COMPLETO;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO DATOS CON EL ID INDICADO');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR' || SQLERRM);
END FIDE_HISTORIAL_MEDICO_PERRITO_FN;


/*
    3. Busca todos los gastos que ha generado el perrito
*/
CREATE OR REPLACE FUNCTION FIDE_GASTOS_POR_PERRO_FN (
    P_ID_PERRITO IN FIDE_PERRITO_TB.ID_PERRITO%TYPE) 
RETURN NUMBER 
IS
    V_TOTAL_GASTOS NUMBER(10,2) := 0;
BEGIN
    FOR REC_GASTO IN (
        SELECT TOTAL_GASTO 
        FROM FIDE_EVENTO_PERRITO_TB 
        WHERE ID_PERRITO = P_ID_PERRITO 
        AND ID_ESTADO = 1
    ) 
    LOOP
        V_TOTAL_GASTOS := V_TOTAL_GASTOS + NVL(REC_GASTO.TOTAL_GASTO, 0);
    END LOOP;
    RETURN V_TOTAL_GASTOS;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO DATOS CON EL ID INDICADO');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR' || SQLERRM);
END FIDE_GASTOS_POR_PERRO_FN;

/*
    4. Busca perritos por filtros
*/
CREATE OR REPLACE FUNCTION FIDE_BUSCAR_PERROS_FILTROS_FN (
    P_EDAD_MAX IN NUMBER,
    P_PESO_MAX IN NUMBER,
    P_ID_SEXO  IN NUMBER) 
RETURN SYS_REFCURSOR 
IS
    V_CURSOR_FILTRO SYS_REFCURSOR;
BEGIN
    OPEN V_CURSOR_FILTRO FOR
        SELECT P.ID_PERRITO, P.NOMBRE, P.EDAD, P.PESO, R.NOMBRE AS RAZA, S.NOMBRE AS SEXO
        FROM FIDE_PERRITO_TB P
        JOIN FIDE_RAZA_TB R ON P.ID_RAZA = R.ID_RAZA
        JOIN FIDE_SEXO_TB S ON P.ID_SEXO = S.ID_SEXO
        WHERE P.ID_ESTADO = 1
          AND (P.EDAD <= P_EDAD_MAX OR P_EDAD_MAX IS NULL)
          AND (P.PESO <= P_PESO_MAX OR P_PESO_MAX IS NULL)
          AND (P.ID_SEXO = P_ID_SEXO OR P_ID_SEXO IS NULL);
          
    RETURN V_CURSOR_FILTRO;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO DATOS CON EL ID INDICADO');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR' || SQLERRM);
END FIDE_BUSCAR_PERROS_FILTROS_FN;

/*
    5. Da cuantos dias de albergue tiene el perrito
*/
CREATE OR REPLACE FUNCTION FIDE_CALCULAR_DIAS_ALBERGUE_FN (
    P_ID_PERRITO IN FIDE_PERRITO_TB.ID_PERRITO%TYPE) 
RETURN NUMBER 
IS
    V_DIAS NUMBER := 0;
    V_FECHA_INGRESO DATE;
BEGIN
    SELECT FECHA_INGRESO INTO V_FECHA_INGRESO
    FROM FIDE_PERRITO_TB
    WHERE ID_PERRITO = P_ID_PERRITO AND ID_ESTADO = 1;

    V_DIAS := TRUNC(SYSDATE) - TRUNC(V_FECHA_INGRESO);
    
    RETURN V_DIAS;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN -1;
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO DATOS CON EL ID INDICADO');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR' || SQLERRM);
END FIDE_CALCULAR_DIAS_ALBERGUE_FN;


/*
    6. Informa su un adoptante es elegible
*/
CREATE OR REPLACE FUNCTION FIDE_ELEGIBILIDAD_ADOPTANTE_FN (
    P_IDENTIFICACION IN FIDE_USUARIO_TB.IDENTIFICACION%TYPE) 
RETURN BOOLEAN 
IS
    V_ES_APTO BOOLEAN := TRUE;
BEGIN
    FOR REC_SEGUIMIENTO IN (
        SELECT S.ID_ESTADO
        FROM FIDE_ADOPCION_TB A
        JOIN FIDE_SEGUIMIENTO_TB S ON A.ID_ADOPCION = S.ID_ADOPCION
        WHERE A.IDENTIFICACION = P_IDENTIFICACION
    ) LOOP
        IF REC_SEGUIMIENTO.ID_ESTADO = 3 THEN
            V_ES_APTO := FALSE;
        END IF;
    END LOOP;

    RETURN V_ES_APTO;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO DATOS CON EL ID INDICADO');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR' || SQLERRM);
END FIDE_ELEGIBILIDAD_ADOPTANTE_FN;


/*
    7. Da el total de donaciones de un mes
*/
CREATE OR REPLACE FUNCTION FIDE_TOTAL_DONACIONES_MES_FN (
    P_MES IN NUMBER,
    P_YEAR IN NUMBER) 
RETURN NUMBER 
IS
    V_TOTAL NUMBER(10,2) := 0;
BEGIN
    FOR REC IN (
        SELECT MONTO 
        FROM FIDE_DONACION_TB
        WHERE EXTRACT(MONTH FROM FECHA_DONACION) = P_MES
          AND EXTRACT(YEAR FROM FECHA_DONACION) = P_YEAR
          AND ID_ESTADO = 1
    ) LOOP
        V_TOTAL := V_TOTAL + REC.MONTO;
    END LOOP;
    
    RETURN V_TOTAL;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO DATOS CON EL ID INDICADO');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR' || SQLERRM);
END FIDE_TOTAL_DONACIONES_MES_FN;


/*
    8. Da el total recaudado de una campaña
*/
CREATE OR REPLACE FUNCTION FIDE_TOTAL_RECAUDADO_CAMPANIA_FN (
    P_ID_CAMPANIA IN FIDE_CAMPANIA_TB.ID_CAMPANIA%TYPE
) 
RETURN NUMBER 
IS
    V_TOTAL NUMBER(10,2) := 0;
BEGIN
    FOR REC IN (
        SELECT MONTO 
        FROM FIDE_DONACION_TB
        WHERE ID_CAMPANIA = P_ID_CAMPANIA
          AND ID_ESTADO = 1
    ) LOOP
        V_TOTAL := V_TOTAL + REC.MONTO;
    END LOOP;
    
    RETURN V_TOTAL;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO DATOS CON EL ID INDICADO');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR' || SQLERRM);
END FIDE_TOTAL_RECAUDADO_CAMPANIA_FN;



/*
    9. Verifica si hay stock suficiente de un producto
*/
CREATE OR REPLACE FUNCTION FIDE_VERIFICAR_STOCK_TIENDA_FN (
    P_ID_PRODUCTO IN FIDE_INVENTARIO_TB.ID_PRODUCTO%TYPE,
    P_CANTIDAD_REQUERIDA IN NUMBER
) 
RETURN BOOLEAN 
IS
    V_STOCK_ACTUAL NUMBER := 0;
BEGIN
    SELECT CANTIDAD INTO V_STOCK_ACTUAL
    FROM FIDE_INVENTARIO_TB
    WHERE ID_PRODUCTO = P_ID_PRODUCTO AND ID_ESTADO = 1;

    IF V_STOCK_ACTUAL >= P_CANTIDAD_REQUERIDA THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN FALSE;
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO DATOS CON EL ID INDICADO');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR' || SQLERRM);
END FIDE_VERIFICAR_STOCK_TIENDA_FN;


/*
    10. Alerta para dar seguimiento a un perrito
*/
CREATE OR REPLACE FUNCTION FIDE_ALERTAS_SEGUIMIENTO_FN
RETURN SYS_REFCURSOR 
IS
    V_CURSOR_ALERTAS SYS_REFCURSOR;
BEGIN
    OPEN V_CURSOR_ALERTAS FOR
        SELECT  S.ID_SEGUIMIENTO,
                A.FECHA_ADOPCION,
                U.NOMBRE || ' ' || U.APELLIDO_PATERNO AS ADOPTANTE,
                U.IDENTIFICACION,
                S.FECHA_FIN
        FROM FIDE_SEGUIMIENTO_TB S
        JOIN FIDE_ADOPCION_TB A ON S.ID_ADOPCION = A.ID_ADOPCION
        JOIN FIDE_USUARIO_TB U ON A.IDENTIFICACION = U.IDENTIFICACION
        WHERE S.ID_ESTADO = 1 
          AND S.FECHA_FIN BETWEEN TRUNC(SYSDATE) AND TRUNC(SYSDATE) + 7
        ORDER BY S.FECHA_FIN ASC;
        
    RETURN V_CURSOR_ALERTAS;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO DATOS CON EL ID INDICADO');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR' || SQLERRM);
END FIDE_ALERTAS_SEGUIMIENTO_FN;


/*
    11. DA cuantos perritos tiene actualmente una casa cuna
*/
CREATE OR REPLACE FUNCTION FIDE_PERRITOS_EN_CASA_CUNA_FN (
    P_IDENTIFICACION IN FIDE_USUARIO_TB.IDENTIFICACION%TYPE) 
RETURN SYS_REFCURSOR 
IS
    V_CURSOR_PERRITOS SYS_REFCURSOR;
BEGIN
    OPEN V_CURSOR_PERRITOS FOR
        SELECT  P.ID_PERRITO,
                P.NOMBRE AS NOMBRE_PERRITO,
                P.PESO,
                CC.NOMBRE AS NOMBRE_CASA_CUNA
        FROM FIDE_CASA_CUNA_TB CC
        JOIN FIDE_CASA_PERRITO_TB CP ON CC.ID_CASA_CUNA = CP.ID_CASA_CUNA
        JOIN FIDE_PERRITO_TB P ON CP.ID_PERRITO = P.ID_PERRITO
        WHERE CC.IDENTIFICACION = P_IDENTIFICACION
          AND CC.ID_ESTADO = 1 
          AND CP.ID_ESTADO = 1;
          
    RETURN V_CURSOR_PERRITOS;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO DATOS CON EL ID INDICADO');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR' || SQLERRM);
END FIDE_PERRITOS_EN_CASA_CUNA_FN;


/*
    12. Verifica si el usuario es administrador o no
*/
CREATE OR REPLACE FUNCTION FIDE_VERIFICAR_PERMISO_ADMIN_FN (
    P_IDENTIFICACION IN FIDE_USUARIO_TB.IDENTIFICACION%TYPE) 
RETURN BOOLEAN 
IS
    V_ID_TIPO_USUARIO NUMBER;
BEGIN
    SELECT ID_TIPO_USUARIO INTO V_ID_TIPO_USUARIO
    FROM FIDE_USUARIO_TB
    WHERE IDENTIFICACION = P_IDENTIFICACION AND ID_ESTADO = 1;

    IF V_ID_TIPO_USUARIO = 1 THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN FALSE;
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO DATOS CON EL ID INDICADO');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR' || SQLERRM);
END FN_VERIFICAR_PERMISO_ADMIN;

/*
    13. Da un reporte de adopciones por año
*/
CREATE OR REPLACE FUNCTION FIDE_ESTADISTICAS_ADOPCION_ANUAL_FN (
    P_YEAR IN NUMBER)
RETURN SYS_REFCURSOR 
IS
    V_CURSOR_ESTADISTICAS SYS_REFCURSOR;
BEGIN
    OPEN V_CURSOR_ESTADISTICAS FOR
        SELECT  EXTRACT(MONTH FROM FECHA_ADOPCION) AS MES,
                COUNT(ID_ADOPCION) AS TOTAL_ADOPCIONES
        FROM FIDE_ADOPCION_TB
        WHERE EXTRACT(YEAR FROM FECHA_ADOPCION) = P_YEAR
          AND ID_ESTADO = 1
        GROUP BY EXTRACT(MONTH FROM FECHA_ADOPCION)
        ORDER BY MES ASC;
        
    RETURN V_CURSOR_ESTADISTICAS;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO DATOS CON EL ID INDICADO');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR' || SQLERRM);
END FIDE_ESTADISTICAS_ADOPCION_ANUAL_FN;


/*
    14. Da un reporte de quien modifico un registro
*/
CREATE OR REPLACE FUNCTION FIDE_ULTIMO_EDITOR_REGISTRO_FN (
    P_ENTIDAD IN FIDE_AUDITORIA_TB.ENTIDAD%TYPE
) RETURN VARCHAR2 
IS
    V_USUARIO FIDE_AUDITORIA_TB.USUARIO%TYPE;
BEGIN
    SELECT USUARIO INTO V_USUARIO
    FROM FIDE_AUDITORIA_TB
    WHERE ENTIDAD = P_ENTIDAD
    ORDER BY FECHA DESC
    FETCH FIRST 1 ROW ONLY;

    RETURN V_USUARIO;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'Sin registros de auditoría';
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO DATOS CON EL ID INDICADO');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR' || SQLERRM);
END FIDE_ULTIMO_EDITOR_REGISTRO_FN;


/*
    15. Da un reporte financiero mensual
*/

CREATE OR REPLACE FUNCTION FIDE_BALANCE_FINANCIERO_MENSUAL_FN (
    P_MES IN NUMBER,
    P_YEAR IN NUMBER
) 
RETURN NUMBER 
IS
    V_TOTAL_DONACIONES NUMBER(10,2) := 0;
    V_TOTAL_VENTAS     NUMBER(10,2) := 0;
    V_TOTAL_GASTOS     NUMBER(10,2) := 0;
    V_BALANCE_NETO     NUMBER(10,2) := 0;
BEGIN
    SELECT NVL(SUM(MONTO), 0) INTO V_TOTAL_DONACIONES
    FROM FIDE_DONACION_TB
    WHERE EXTRACT(MONTH FROM FECHA_DONACION) = P_MES
      AND EXTRACT(YEAR FROM FECHA_DONACION) = P_YEAR AND ID_ESTADO = 1;

    SELECT NVL(SUM(TOTAL_VENTA), 0) INTO V_TOTAL_VENTAS
    FROM FIDE_VENTA_TB
    WHERE EXTRACT(MONTH FROM FECHA_VENTA) = P_MES
      AND EXTRACT(YEAR FROM FECHA_VENTA) = P_YEAR AND ID_ESTADO = 1;

    SELECT NVL(SUM(TOTAL_GASTO), 0) INTO V_TOTAL_GASTOS
    FROM FIDE_EVENTO_PERRITO_TB
    WHERE EXTRACT(MONTH FROM FECHA_EVENTO) = P_MES
      AND EXTRACT(YEAR FROM FECHA_EVENTO) = P_YEAR AND ID_ESTADO = 1;

    V_BALANCE_NETO := (V_TOTAL_DONACIONES + V_TOTAL_VENTAS) - V_TOTAL_GASTOS;

    RETURN V_BALANCE_NETO;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO DATOS CON EL ID INDICADO');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('DATOS DUPLICADOS');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR' || SQLERRM);
END FIDE_BALANCE_FINANCIERO_MENSUAL_FN;