/* ESQUEMA */

-- CREACION DE USUARIO Y ASIGNACION DE PRIVILEGIOS
CREATE USER KALO IDENTIFIED BY "Adopciones_fidelitas$2026";
/

GRANT CREATE SESSION TO KALO;
/

GRANT RESOURCE TO KALO;
/

ALTER USER KALO QUOTA 500M ON USERS;
/

-- ============================================================
-- TABLAS BASE (SOLO DEPENDEN DE FIDE_ESTADO_TB)
-- ============================================================

CREATE TABLE FIDE_ESTADO_TB(
    ID_ESTADO       NUMBER,
    NOMBRE_ESTADO   VARCHAR(100),
    CONSTRAINT FIDE_ESTADO_PK_TB PRIMARY KEY (ID_ESTADO)
);
/

CREATE TABLE FIDE_TIPO_USUARIO_TB(
    ID_TIPO_USUARIO NUMBER,
    NOMBRE VARCHAR2(100),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_TIPO_USUARIO_PK_ID_TIPO_USUARIO PRIMARY KEY(ID_TIPO_USUARIO),
    CONSTRAINT FIDE_TIPO_USUARIO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_PAIS_TB(
    ID_PAIS NUMBER,
    NOMBRE VARCHAR2(100),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_PAIS_PK_ID_PAIS PRIMARY KEY(ID_PAIS),
    CONSTRAINT FIDE_PAIS_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_TIPO_OTP_TB(
    ID_TIPO_OTP NUMBER,
    NOMBRE VARCHAR2(100),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_TIPO_OTP_PK_ID_TIPO_OTP PRIMARY KEY(ID_TIPO_OTP),
    CONSTRAINT FIDE_TIPO_OTP_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_CATEGORIA_TB(
    ID_CATEGORIA NUMBER,
    NOMBRE VARCHAR2(100),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_CATEGORIA_PK_ID_CATEGORIA PRIMARY KEY(ID_CATEGORIA),
    CONSTRAINT FIDE_CATEGORIA_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_TIPO_MOVIMIENTO_TB(
    ID_TIPO_MOVIMIENTO NUMBER,
    NOMBRE VARCHAR2(100),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_TIPO_MOVIMIENTO_PK_ID_TIPO_MOVIMIENTO PRIMARY KEY(ID_TIPO_MOVIMIENTO),
    CONSTRAINT FIDE_TIPO_MOVIMIENTO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_CAMPANIA_TB(
    ID_CAMPANIA NUMBER,
    NOMBRE VARCHAR2(100),
    DESCRIPCION VARCHAR2(500),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_CAMPANIA_PK_ID_CAMPANIA PRIMARY KEY(ID_CAMPANIA),
    CONSTRAINT FIDE_CAMPANIA_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_MONEDA_TB(
    ID_MONEDA NUMBER,
    NOMBRE VARCHAR2(100),
    SIMBOLO VARCHAR2(10),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_MONEDA_PK_ID_MONEDA PRIMARY KEY(ID_MONEDA),
    CONSTRAINT FIDE_MONEDA_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_RAZA_TB(
    ID_RAZA NUMBER,
    NOMBRE VARCHAR2(100),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_RAZA_PK_ID_RAZA PRIMARY KEY(ID_RAZA),
    CONSTRAINT FIDE_RAZA_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_SEXO_TB(
    ID_SEXO NUMBER,
    NOMBRE VARCHAR2(100),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_SEXO_PK_ID_SEXO PRIMARY KEY(ID_SEXO),
    CONSTRAINT FIDE_SEXO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_TIPO_SOLICITUD_TB(
    ID_TIPO_SOLICITUD NUMBER,
    NOMBRE VARCHAR2(100),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_TIPO_SOLICITUD_PK_ID_TIPO_SOLICITUD PRIMARY KEY(ID_TIPO_SOLICITUD),
    CONSTRAINT FIDE_TIPO_SOLICITUD_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_TIPO_RESPUESTA_TB(
    ID_TIPO_RESPUESTA NUMBER,
    NOMBRE VARCHAR2(100),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_TIPO_RESPUESTA_PK_ID_TIPO_RESPUESTA PRIMARY KEY(ID_TIPO_RESPUESTA),
    CONSTRAINT FIDE_TIPO_RESPUESTA_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_TIPO_SEGUIMIENTO(
    ID_TIPO_SEGUIMIENTO NUMBER,
    NOMBRE VARCHAR2(100),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_TIPO_SEGUIMIENTO_PK_ID_TIPO_SEGUIMIENTO PRIMARY KEY(ID_TIPO_SEGUIMIENTO),
    CONSTRAINT FIDE_TIPO_SEGUIMIENTO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_TIPO_EVENTO_TB(
    ID_TIPO_EVENTO NUMBER,
    NOMBRE VARCHAR2(100),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_TIPO_EVENTO_PK_ID_TIPO_EVENTO PRIMARY KEY(ID_TIPO_EVENTO),
    CONSTRAINT FIDE_TIPO_EVENTO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

-- ============================================================
-- TABLAS QUE DEPENDEN DE LAS ANTERIORES (SIN USUARIO AÚN)
-- ============================================================

CREATE TABLE FIDE_PROVINCIA_TB(
    ID_PROVINCIA NUMBER,
    NOMBRE VARCHAR2(100),
    ID_PAIS NUMBER,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_PROVINCIA_PK_ID_PROVINCIA PRIMARY KEY(ID_PROVINCIA),
    CONSTRAINT FIDE_PROVINCIA_FK_ID_PAIS FOREIGN KEY(ID_PAIS)
        REFERENCES FIDE_PAIS_TB(ID_PAIS),
    CONSTRAINT FIDE_PROVINCIA_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_CANTON_TB(
    ID_CANTON NUMBER,
    NOMBRE VARCHAR2(100),
    ID_PROVINCIA NUMBER,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_CANTON_PK_ID_CANTON PRIMARY KEY(ID_CANTON),
    CONSTRAINT FIDE_CANTON_FK_ID_PROVINCIA FOREIGN KEY(ID_PROVINCIA)
        REFERENCES FIDE_PROVINCIA_TB(ID_PROVINCIA),
    CONSTRAINT FIDE_CANTON_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_DISTRITO_TB(
    ID_DISTRITO NUMBER,
    NOMBRE VARCHAR2(100),
    ID_CANTON NUMBER,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_DISTRITO_PK_ID_DISTRITO PRIMARY KEY(ID_DISTRITO),
    CONSTRAINT FIDE_DISTRITO_FK_ID_CANTON FOREIGN KEY(ID_CANTON)
        REFERENCES FIDE_CANTON_TB(ID_CANTON),
    CONSTRAINT FIDE_DISTRITO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_DIRECCION_TB(
    ID_DIRECCION NUMBER,
    ID_DISTRITO NUMBER,
    CALLE VARCHAR2(100),
    NUMERO VARCHAR2(100),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_DIRECCION_PK_ID_DIRECCION PRIMARY KEY(ID_DIRECCION),
    CONSTRAINT FIDE_DIRECCION_FK_ID_DISTRITO FOREIGN KEY(ID_DISTRITO)
        REFERENCES FIDE_DISTRITO_TB(ID_DISTRITO),
    CONSTRAINT FIDE_DIRECCION_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_PRODUCTO_TB(
    ID_PRODUCTO NUMBER,
    NOMBRE VARCHAR2(100),
    DESCRIPCION VARCHAR2(500),
    PRECIO NUMBER(10,2),
    ID_CATEGORIA NUMBER,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_PRODUCTO_PK_ID_PRODUCTO PRIMARY KEY(ID_PRODUCTO),
    CONSTRAINT FIDE_PRODUCTO_FK_ID_CATEGORIA FOREIGN KEY(ID_CATEGORIA)
        REFERENCES FIDE_CATEGORIA_TB(ID_CATEGORIA),
    CONSTRAINT FIDE_PRODUCTO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_PREGUNTA_TB(
    ID_PREGUNTA NUMBER,
    PREGUNTA VARCHAR2(500),
    ID_TIPO_RESPUESTA NUMBER,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_PREGUNTA_PK_ID_PREGUNTA PRIMARY KEY(ID_PREGUNTA),
    CONSTRAINT FIDE_PREGUNTA_FK_ID_TIPO_RESPUESTA FOREIGN KEY(ID_TIPO_RESPUESTA)
        REFERENCES FIDE_TIPO_RESPUESTA_TB(ID_TIPO_RESPUESTA),
    CONSTRAINT FIDE_PREGUNTA_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

-- ============================================================
-- TABLA USUARIO (DEPENDE DE DIRECCIÓN Y TIPO USUARIO)
-- ============================================================

CREATE TABLE FIDE_USUARIO_TB(
    IDENTIFICACION NUMBER,
    NOMBRE VARCHAR2(100),
    APELLIDO_PATERNO VARCHAR2(100),
    APELLIDO_MATERNO VARCHAR2(100),
    FECHA_REGISTRO DATE DEFAULT SYSDATE,
    ID_DIRECCION NUMBER,
    ID_TIPO_USUARIO NUMBER,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_USUARIO_PK_IDENTIFICACION PRIMARY KEY(IDENTIFICACION),
    CONSTRAINT FIDE_USUARIO_FK_ID_DIRECCION FOREIGN KEY(ID_DIRECCION)
        REFERENCES FIDE_DIRECCION_TB(ID_DIRECCION),
    CONSTRAINT FIDE_USUARIO_FK_ID_TIPO_USUARIO FOREIGN KEY(ID_TIPO_USUARIO)
        REFERENCES FIDE_TIPO_USUARIO_TB(ID_TIPO_USUARIO),
    CONSTRAINT FIDE_USUARIO_FK__ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

-- ============================================================
-- TABLAS QUE DEPENDEN DIRECTAMENTE DE USUARIO
-- ============================================================

CREATE TABLE FIDE_CORREO_TB(
    IDENTIFICACION NUMBER,
    CORREO VARCHAR2(100)
    CONSTRAINT CORREO_UNIQUE UNIQUE
    CONSTRAINT CORREO_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_CORREO_PK_IDENTIFICACION_CORREO PRIMARY KEY(IDENTIFICACION, CORREO),
    CONSTRAINT FIDE_CORREO_FK_IDENTIFICACION FOREIGN KEY(IDENTIFICACION)
        REFERENCES FIDE_USUARIO_TB(IDENTIFICACION),
    CONSTRAINT FIDE_CORREO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_TELEFONO_TB(
    IDENTIFICACION NUMBER,
    TELEFONO VARCHAR2(100)
    CONSTRAINT TELEFONO_UNIQUE UNIQUE
    CONSTRAINT TELEFONO_NOT_NULL NOT NULL,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_TELEFONO_PK_IDENTIFICACION_TELEFONO PRIMARY KEY(IDENTIFICACION, TELEFONO),
    CONSTRAINT FIDE_TELEFONO_FK_IDENTIFICACION FOREIGN KEY(IDENTIFICACION)
        REFERENCES FIDE_USUARIO_TB(IDENTIFICACION),
    CONSTRAINT FIDE_TELEFONO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_CUENTA_TB(
    ID_CUENTA NUMBER,
    IDENTIFICACION NUMBER,
    USUARIO VARCHAR2(100),
    PASSWORD_HASH VARCHAR2(255)
    CONSTRAINT PASSWORD_HASH_NOT_NULL NOT NULL,
    FECHA_REGISTRO DATE DEFAULT SYSDATE,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_CUENTA_PK_ID_CUENTA PRIMARY KEY(ID_CUENTA),
    CONSTRAINT FIDE_CUENTA_FK_IDENTIFICACION FOREIGN KEY(IDENTIFICACION)
        REFERENCES FIDE_USUARIO_TB(IDENTIFICACION),
    CONSTRAINT FIDE_CUENTA_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_CODIGO_OTP_TB(
    ID_CODIGO_OTP NUMBER,
    ID_CUENTA NUMBER,
    ID_TIPO_OTP NUMBER,
    CODIGO_HASH VARCHAR2(200),
    FECHA_EXPIRACION DATE,
    FECHA_USO DATE,
    INTENTOS NUMBER,
    FECHA_CREACION DATE DEFAULT SYSDATE,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_CODIGO_OTP_PK_ID_CODIGO_OTP PRIMARY KEY(ID_CODIGO_OTP),
    CONSTRAINT FIDE_CODIGO_OTP_FK_ID_CUENTA FOREIGN KEY(ID_CUENTA)
        REFERENCES FIDE_CUENTA_TB(ID_CUENTA),
    CONSTRAINT FIDE_CODIGO_OTP_FK_ID_TIPO_OTP FOREIGN KEY(ID_TIPO_OTP)
        REFERENCES FIDE_TIPO_OTP_TB(ID_TIPO_OTP),
    CONSTRAINT FIDE_CODIGO_OTP_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_REFRESH_TOKEN_TB(
    ID_REFRESH_TOKEN NUMBER,
    ID_CUENTA NUMBER,
    TOKEN_HASH VARCHAR2(500),
    JTI VARCHAR2(100),
    IP_ADDRESS VARCHAR2(100),
    USER_AGENT VARCHAR2(300),
    FECHA_EXPIRACION DATE,
    FECHA_REVOCACION DATE,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_REFRESH_TOKEN_PK_ID_REFRESH_TOKEN PRIMARY KEY(ID_REFRESH_TOKEN),
    CONSTRAINT FIDE_REFRESH_TOKEN_FK_ID_CUENTA FOREIGN KEY(ID_CUENTA)
        REFERENCES FIDE_CUENTA_TB(ID_CUENTA),
    CONSTRAINT FIDE_REFRESH_TOKEN_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_VENTA_TB(
    ID_VENTA NUMBER,
    IDENTIFICACION NUMBER,
    TOTAL_VENTA NUMBER(10,2),
    FECHA_VENTA DATE,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_VENTA_PK_ID_VENTA PRIMARY KEY(ID_VENTA),
    CONSTRAINT FIDE_VENTA_FK_IDENTIFICACION FOREIGN KEY(IDENTIFICACION)
        REFERENCES FIDE_USUARIO_TB(IDENTIFICACION),
    CONSTRAINT FIDE_VENTA_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_DONACION_TB(
    ID_DONACION NUMBER,
    IDENTIFICACION NUMBER,
    ID_CAMPANIA NUMBER,
    MONTO NUMBER(10,2),
    FECHA_DONACION DATE,
    MENSAJE VARCHAR2(500),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_DONACION_PK_ID_DONACION PRIMARY KEY(ID_DONACION),
    CONSTRAINT FIDE_DONACION_FK_IDENTIFICACION FOREIGN KEY(IDENTIFICACION)
        REFERENCES FIDE_USUARIO_TB(IDENTIFICACION),
    CONSTRAINT FIDE_DONACION_FK_ID_CAMPANIA FOREIGN KEY(ID_CAMPANIA)
        REFERENCES FIDE_CAMPANIA_TB(ID_CAMPANIA),
    CONSTRAINT FIDE_DONACION_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_AUDITORIA_TB(
    ID_AUDITORIA NUMBER,
    IDENTIFICACION NUMBER,
    ENTIDAD VARCHAR2(100),
    ACCION VARCHAR2(100),
    USUARIO VARCHAR2(100),
    FECHA DATE,
    DETALLE VARCHAR2(500),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_AUDITORIA_PK_ID_AUDITORIA PRIMARY KEY(ID_AUDITORIA),
    CONSTRAINT FIDE_AUDITORIA_FK_IDENTIFICACION FOREIGN KEY(IDENTIFICACION)
        REFERENCES FIDE_USUARIO_TB(IDENTIFICACION),
    CONSTRAINT FIDE_AUDITORIA_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
         REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

-- ============================================================
-- MÓDULO PERRITOS (DEPENDE DE RAZA, SEXO)
-- ============================================================

CREATE TABLE FIDE_PERRITO_TB(
    ID_PERRITO NUMBER,
    NOMBRE VARCHAR2(100),
    FECHA_INGRESO DATE,
    EDAD NUMBER,
    PESO NUMBER,
    ESTATURA NUMBER,
    ID_SEXO NUMBER,
    ID_RAZA NUMBER,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_PERRITO_PK_ID_PERRITO PRIMARY KEY(ID_PERRITO),
    CONSTRAINT FIDE_PERRITO_FK_ID_SEXO FOREIGN KEY(ID_SEXO)
        REFERENCES FIDE_SEXO_TB(ID_SEXO),
    CONSTRAINT FIDE_PERRITO_FK_ID_RAZA FOREIGN KEY(ID_RAZA)
        REFERENCES FIDE_RAZA_TB(ID_RAZA),
    CONSTRAINT FIDE_PERRITO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_PERRITO_IMAGE_TB(
    ID_IMAGEN NUMBER,
    ID_PERRITO NUMBER,
    IMAGE_URL VARCHAR2(500),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_PERRITO_IMAGE_PK_ID_PERRITO_IMAGE PRIMARY KEY(ID_IMAGEN),
    CONSTRAINT FIDE_PERRITO_IMAGE_FK_ID_PERRITO FOREIGN KEY(ID_PERRITO)
        REFERENCES FIDE_PERRITO_TB(ID_PERRITO),
    CONSTRAINT FIDE_PERRITO_IMAGE_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_EVENTO_PERRITO_TB(
    ID_EVENTO NUMBER,
    ID_PERRITO NUMBER,
    ID_TIPO_EVENTO NUMBER,
    FECHA_EVENTO DATE,
    DETALLE VARCHAR2(500),
    TOTAL_GASTO NUMBER(10,2),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_EVENTO_PERRITO_PK_ID_EVENTO PRIMARY KEY(ID_EVENTO),
    CONSTRAINT FIDE_EVENTO_PERRITO_FK_ID_PERRITO FOREIGN KEY(ID_PERRITO)
        REFERENCES FIDE_PERRITO_TB(ID_PERRITO),
    CONSTRAINT FIDE_EVENTO_PERRITO_FK_ID_TIPO_EVENTO FOREIGN KEY(ID_TIPO_EVENTO)
        REFERENCES FIDE_TIPO_EVENTO_TB(ID_TIPO_EVENTO),
    CONSTRAINT FIDE_EVENTO_PERRITO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_DETALLE_EVENTO_TB(
    ID_DETALLE_EVENTO NUMBER,
    ID_EVENTO NUMBER,
    COMPROBANTE_URL VARCHAR2(500),
    DESCRIPCION VARCHAR2(500),
    MONTO NUMBER(10,2),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_DETALLE_EVENTO_PK_ID_DETALLE_EVENTO PRIMARY KEY(ID_DETALLE_EVENTO),
    CONSTRAINT FIDE_DETALLE_EVENTO_FK_ID_EVENTO FOREIGN KEY(ID_EVENTO)
        REFERENCES FIDE_EVENTO_PERRITO_TB(ID_EVENTO),
    CONSTRAINT FIDE_DETALLE_EVENTO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

-- ============================================================
-- MÓDULO SOLICITUD (DEPENDE DE USUARIO, PERRITO, TIPO_SOLICITUD, PREGUNTA)
-- ============================================================

CREATE TABLE FIDE_SOLICITUD_TB(
    ID_SOLICITUD NUMBER,
    IDENTIFICACION NUMBER,
    ID_PERRITO NUMBER,
    ID_TIPO_SOLICITUD NUMBER,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_SOLICITUD_PK_ID_SOLICITUD PRIMARY KEY(ID_SOLICITUD),
    CONSTRAINT FIDE_SOLICITUD_FK_IDENTIFICACION FOREIGN KEY(IDENTIFICACION)
        REFERENCES FIDE_USUARIO_TB(IDENTIFICACION),
    CONSTRAINT FIDE_SOLICITUD_FK_ID_PERRITO FOREIGN KEY(ID_PERRITO)
        REFERENCES FIDE_PERRITO_TB(ID_PERRITO),
    CONSTRAINT FIDE_SOLICITUD_FK_ID_TIPO_SOLICITUD FOREIGN KEY(ID_TIPO_SOLICITUD)
        REFERENCES FIDE_TIPO_SOLICITUD_TB(ID_TIPO_SOLICITUD),
    CONSTRAINT FIDE_SOLICITUD_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_RESPUESTA_TB(
    ID_RESPUESTA NUMBER,
    ID_SOLICITUD NUMBER,
    ID_PREGUNTA NUMBER,
    RESPUESTA VARCHAR2(500),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_RESPUESTA_PK_ID_RESPUESTA PRIMARY KEY(ID_RESPUESTA),
    CONSTRAINT FIDE_RESPUESTA_FK_ID_SOLICITUD FOREIGN KEY(ID_SOLICITUD)
        REFERENCES FIDE_SOLICITUD_TB(ID_SOLICITUD),
    CONSTRAINT FIDE_RESPUESTA_FK_ID_PREGUNTA FOREIGN KEY(ID_PREGUNTA)
        REFERENCES FIDE_PREGUNTA_TB(ID_PREGUNTA),
    CONSTRAINT FIDE_RESPUESTA_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_CASA_CUNA_TB(
    ID_CASA_CUNA NUMBER,
    NOMBRE VARCHAR2(100),
    ID_DIRECCION NUMBER,
    IDENTIFICACION NUMBER,
    ID_SOLICITUD NUMBER,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_CASA_CUNA_PK_ID_CASA_CUNA PRIMARY KEY(ID_CASA_CUNA),
    CONSTRAINT FIDE_CASA_CUNA_FK_ID_DIRECCION FOREIGN KEY(ID_DIRECCION)
        REFERENCES FIDE_DIRECCION_TB(ID_DIRECCION),
    CONSTRAINT FIDE_CASA_CUNA_FK_IDENTIFICACION FOREIGN KEY(IDENTIFICACION)
        REFERENCES FIDE_USUARIO_TB(IDENTIFICACION),
    CONSTRAINT FIDE_CASA_CUNA_FK_ID_SOLICITUD FOREIGN KEY(ID_SOLICITUD)
        REFERENCES FIDE_SOLICITUD_TB(ID_SOLICITUD),
    CONSTRAINT FIDE_CASA_CUNA_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_ADOPCION_TB(
    ID_ADOPCION NUMBER,
    IDENTIFICACION NUMBER,
    ID_SOLICITUD NUMBER,
    FECHA_ADOPCION DATE,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_ADOPCION_PK_ID_ADOPCION PRIMARY KEY(ID_ADOPCION),
    CONSTRAINT FIDE_ADOPCION_FK_IDENTIFICACION FOREIGN KEY(IDENTIFICACION)
        REFERENCES FIDE_USUARIO_TB(IDENTIFICACION),
    CONSTRAINT FIDE_ADOPCION_FK_ID_SOLICITUD FOREIGN KEY(ID_SOLICITUD)
        REFERENCES FIDE_SOLICITUD_TB(ID_SOLICITUD),
    CONSTRAINT FIDE_ADOPCION_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_SEGUIMIENTO_TB(
    ID_SEGUIMIENTO NUMBER,
    ID_ADOPCION NUMBER,
    ID_TIPO_SEGUIMIENTO NUMBER,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    COMENTARIOS VARCHAR2(500),
    ID_ESTADO NUMBER,
    CONSTRAINT SEGUIMIENTO_RESPONSABILIDAD_PK_ID_SEGUIMIENTO PRIMARY KEY(ID_SEGUIMIENTO),
    CONSTRAINT SEGUIMIENTO_RESPONSABILIDAD_FK_ID_ADOPCION FOREIGN KEY(ID_ADOPCION)
        REFERENCES FIDE_ADOPCION_TB(ID_ADOPCION),
    CONSTRAINT SEGUIMIENTO_RESPONSABILIDAD_FK_ID_TIPO_SEGUIMIENTO FOREIGN KEY(ID_TIPO_SEGUIMIENTO)
        REFERENCES FIDE_TIPO_SEGUIMIENTO(ID_TIPO_SEGUIMIENTO),
    CONSTRAINT SEGUIMIENTO_RESPONSABILIDAD_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_EVIDENCIA_TB(
    ID_EVIDENCIA NUMBER,
    ID_SEGUIMIENTO NUMBER,
    IMAGEN_URL VARCHAR2(500),
    COMENTARIOS VARCHAR2(500),
    FECHA_EVIDENCIA DATE,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_EVIDENCIA_PK_ID_EVIDENCIA PRIMARY KEY(ID_EVIDENCIA),
    CONSTRAINT FIDE_EVIDENCIA_FK_ID_SEGUIMIENTO FOREIGN KEY(ID_SEGUIMIENTO)
        REFERENCES FIDE_SEGUIMIENTO_TB(ID_SEGUIMIENTO),
    CONSTRAINT FIDE_EVIDENCIA_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_CASA_PERRITO_TB(
    ID_CASA_CUNA NUMBER,
    ID_PERRITO NUMBER,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_CASA_PERRITO_PK_ID_CASA_CUNA_ID_PERRITO PRIMARY KEY(ID_CASA_CUNA, ID_PERRITO),
    CONSTRAINT FIDE_CASA_PERRITO_FK_ID_CASA_CUNA FOREIGN KEY(ID_CASA_CUNA)
        REFERENCES FIDE_CASA_CUNA_TB(ID_CASA_CUNA),
    CONSTRAINT FIDE_CASA_PERRITO_FK_ID_PERRITO FOREIGN KEY(ID_PERRITO)
        REFERENCES FIDE_PERRITO_TB(ID_PERRITO),
    CONSTRAINT FIDE_CASA_PERRITO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

-- ============================================================
-- MÓDULO FACTURACIÓN (DEPENDE DE MONEDA, VENTA, DONACIÓN)
-- ============================================================

CREATE TABLE FIDE_FACTURA_TB(
    ID_FACTURA NUMBER,
    ID_MONEDA NUMBER,
    IMPUESTO NUMBER(10,2),
    SUBTOTAL NUMBER(10,2),
    TOTAL NUMBER(10,2),
    FECHA_FACTURA DATE,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_FACTURA_PK_ID_FACTURA PRIMARY KEY(ID_FACTURA),
    CONSTRAINT FIDE_FACTURA_FK_ID_MONEDA FOREIGN KEY(ID_MONEDA)
        REFERENCES FIDE_MONEDA_TB(ID_MONEDA),
    CONSTRAINT FIDE_FACTURA_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_VENTA_FACTURA_TB(
    ID_VENTA NUMBER,
    ID_FACTURA NUMBER,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_VENTA_FACTURA_PK_ID_VENTA_ID_FACTURA PRIMARY KEY(ID_VENTA, ID_FACTURA),
    CONSTRAINT FIDE_VENTA_FACTURA_FK_ID_VENTA FOREIGN KEY(ID_VENTA)
        REFERENCES FIDE_VENTA_TB(ID_VENTA),
    CONSTRAINT FIDE_VENTA_FACTURA_FK_ID_FACTURA FOREIGN KEY(ID_FACTURA)
        REFERENCES FIDE_FACTURA_TB(ID_FACTURA),
    CONSTRAINT FIDE_VENTA_FACTURA_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_DONACION_FACTURA_TB(
    ID_DONACION NUMBER,
    ID_FACTURA NUMBER,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_DONACION_FACTURA_PK_ID_DONACION_ID_FACTURA PRIMARY KEY(ID_DONACION, ID_FACTURA),
    CONSTRAINT FIDE_DONACION_FACTURA_FK_ID_DONACION FOREIGN KEY(ID_DONACION)
        REFERENCES FIDE_DONACION_TB(ID_DONACION),
    CONSTRAINT FIDE_DONACION_FACTURA_FK_ID_FACTURA FOREIGN KEY(ID_FACTURA)
        REFERENCES FIDE_FACTURA_TB(ID_FACTURA),
    CONSTRAINT FIDE_DONACION_FACTURA_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_PAGO_PAYPAL_TB(
    ID_PAGO NUMBER,
    ID_FACTURA NUMBER,
    PAYPAL_ORDER_ID VARCHAR2(100),
    PAYPAL_CAPTURE_ID VARCHAR2(100),
    FECHA_PAGO DATE,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_PAGO_PAYPAL_PK_ID_PAGO PRIMARY KEY(ID_PAGO),
    CONSTRAINT FIDE_PAGO_PAYPAL_FK_ID_FACTURA FOREIGN KEY(ID_FACTURA)
        REFERENCES FIDE_FACTURA_TB(ID_FACTURA),
    CONSTRAINT FIDE_PAGO_PAYPAL_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

-- ============================================================
-- MÓDULO INVENTARIO (DEPENDE DE PRODUCTO, TIPO_MOVIMIENTO)
-- ============================================================

CREATE TABLE FIDE_INVENTARIO_TB(
    ID_INVENTARIO NUMBER,
    ID_PRODUCTO NUMBER,
    CANTIDAD NUMBER,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_INVENTARIO_PK_ID_INVENTARIO PRIMARY KEY(ID_INVENTARIO),
    CONSTRAINT FIDE_INVENTARIO_FK_ID_PRODUCTO FOREIGN KEY(ID_PRODUCTO)
        REFERENCES FIDE_PRODUCTO_TB(ID_PRODUCTO),
    CONSTRAINT FIDE_INVENTARIO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_MOVIMIENTO_INVENTARIO_TB(
    ID_MOVIMIENTO NUMBER,
    ID_PRODUCTO NUMBER,
    ID_TIPO_MOVIMIENTO NUMBER,
    CANTIDAD NUMBER,
    FECHA_MOVIMIENTO DATE,
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_MOVIMIENTO_INVENTARIO_PK_ID_MOVIMIENTO PRIMARY KEY(ID_MOVIMIENTO),
    CONSTRAINT FIDE_MOVIMIENTO_INVENTARIO_FK_ID_PRODUCTO FOREIGN KEY(ID_PRODUCTO)
        REFERENCES FIDE_PRODUCTO_TB(ID_PRODUCTO),
    CONSTRAINT FIDE_MOVIMIENTO_INVENTARIO_FK_ID_TIPO_MOVIMIENTO FOREIGN KEY(ID_TIPO_MOVIMIENTO)
        REFERENCES FIDE_TIPO_MOVIMIENTO_TB(ID_TIPO_MOVIMIENTO),
    CONSTRAINT FIDE_MOVIMIENTO_INVENTARIO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/

-- ============================================================
-- TABLA VENTA_PRODUCTO (DEPENDE DE VENTA Y PRODUCTO)
-- ============================================================

CREATE TABLE FIDE_VENTA_PRODUCTO_TB(
    ID_VENTA NUMBER,
    ID_PRODUCTO NUMBER,
    ID_TIPO_MOVIMIENTO NUMBER,
    CANTIDAD NUMBER,
    TOTAL NUMBER(10,2),
    ID_ESTADO NUMBER,
    CONSTRAINT FIDE_VENTA_PRODUCTO_PK_ID_VENTA_ID_PRODUCTO PRIMARY KEY(ID_VENTA, ID_PRODUCTO),
    CONSTRAINT FIDE_VENTA_PRODUCTO_FK_ID_VENTA FOREIGN KEY(ID_VENTA)
        REFERENCES FIDE_VENTA_TB(ID_VENTA),
    CONSTRAINT FIDE_VENTA_PRODUCTO_FK_ID_PRODUCTO FOREIGN KEY(ID_PRODUCTO)
        REFERENCES FIDE_PRODUCTO_TB(ID_PRODUCTO),
    CONSTRAINT FIDE_VENTA_PRODUCTO_FK_ID_ESTADO FOREIGN KEY(ID_ESTADO)
        REFERENCES FIDE_ESTADO_TB(ID_ESTADO)
);
/