/*

        1. CATALOGO DE PERRITOS EN ADOPCION

*/
CREATE OR REPLACE VIEW FIDE_CATALOGO_PERRITOS_V AS
SELECT  P.ID_PERRITO,
        P.NOMBRE AS NOMBRE_PERRITO,
        P.FECHA_INGRESO,
        P.EDAD,
        P.ESTATURA,
        S.NOMBRE AS SEXO,
        R.NOMBRE AS RAZA,
        PI.IMAGE_URL
FROM FIDE_PERRITO_TB P
JOIN FIDE_SEXO_TB S ON P.ID_SEXO = S.ID_SEXO
JOIN FID_RAZA_TB R ON P.ID_RAZA = R.ID_RAZA
LEFT JOIN FIDE_PERRITO_IMAGE_TB PI ON P.ID_PERRITO = PI.ID_PERRITO AND PI.ID_ESTADO = 1
WHERE P.ID_ESTADO = 1;

/*

        2. VISTA COMPLETA DEL PERFIL

*/
CREATE OR REPLACE VIEW FIDE_PERFIL_USUARIO_V AS
SELECT  U.IDENTIFICACION,
        U.NOMBRE,
        U.APELLIDO_PATERNO,
        U.APELLIDO_MATERNO,
        TU.NOMBRE AS TIPO_USUARIO,
        U.FECHA_REGISTRO,
        DIS.NOMBRE AS DISTRITO,
        C.NOMBRE AS CANTON,
        PR.NOMBRE AS PROVINCIA,
        PA.NOMBRE AS PAIS
FROM FIDE_USUARIO_TB U
JOIN FIDE_TIPO_USUARIO_TB TU ON U.ID_TIPO_USUARIO = TU.ID_TIPO_USUARIO
LEFT JOIN FIDE_DIRECCION_TB DIR ON U.ID_DIRECCION = DIR.ID_DIRECCION
JOIN FIDE_DISTRITO_TB DIS ON DIR.ID_DISTRITO = DIS.ID_DISTRITO
JOIN FIDE_CANTON_TB C ON DIS.ID_CANTON = C.ID_CANTON
JOIN FIDE_PROVINCIA_TB PR ON C.ID_PROVINCIA = PR.ID_PROVINCIA
JOIN FIDE_PAIS_TB PA ON PR.ID_PAIS = PA.ID_PAIS
WHERE U.ID_ESTADO = 1;

/*

       3. CATALOGO DE PRODUCTOS DE LA TIENDA SOLIDARIA

*/
CREATE OR REPLACE VIEW FIDE_TIENDA_SOLIDARIA_V AS
SELECT  P.ID_PRODUCTO,
        P.NOMBRE AS PRODUCTO,
        P.DESCRIPCION,
        P.PRECIO
        C.NOMBRE AS CATEGORIA,
        NVL(I.CANTIDAD, 0) AS STOCK
FROM FIDE_PRODUCTO_TB P
JOIN FIDE_CATEGORIA_TB C ON P.ID_CATEGORIA = C.ID_CATEGORIA
LEFT JOIN FIDE_INVENTARIO_TB I ON P.ID_PRODUCTO = I.ID_PRODUCTO AND I.ID_ESTADO = 1
WHERE P.ID_ESTADO = 1 AND I.CANTIDAD > 0;

/*

       4. VISTA DE SOLICITUDES ENTRANTES

*/
CREATE OR REPLACE VIEW FIDE_PANEL_SOLICITUDES_V AS
SELECT  S.ID_SOLICITUD,
        TS.NOMBRE AS TIPO_SOLICITUD,
        U.IDENTIFICACION AS ID_SOLICITANTE,
        U.NOMBRE || ' ' || U.APELLIDO_PATERNO AS SOLICITANTE,
        P.NOMBRE AS NOMBRE_PERRITO,
        E.NOMBRE_ESTADO AS ESTADO_SOLICITUD
FROM FIDE_SOLICITUD_TB S
JOIN FIDE_TIPO_SOLICITUD_TB TS ON S.ID_TIPO_SOLICITUD = TS.ID_TIPO_SOLICITUD
JOIN FIDE_USUARIO_TB U ON S.IDENTIFICACION = U.IDENTIFICACION
LEFT JOIN FIDE_PERRITO_TB P ON S.ID_PERRITO = P.ID_PERRITO
JOIN FIDE_ESTADO_TB E ON S.ID_ESTADO = E.ID_ESTADO;

/*

       5. CONTROL DE SEGUIMIENTO DE ADOPCIONES

*/
CREATE OR REPLACE VIEW FIDE_SEGUIMIENTO_ADOPCIONES_V AS
SELECT  SEG.ID_SEGUIMIENTO,
        TS.NOMBRE AS TIPO_SEGUIMIENTO,
        ADOP.FECHA_ADOPCION,
        U.NOMBRE || ' ' || U.APELLIDO_PATERNO AS FAMILIA_ADOPTANTE,
        U.IDENTIFICACION AS CONTACTO_FAMILIA,
        SEG.FECHA_INICIO,
        SEG.FECHA_FIN,
        SEG.COMENTARIOS,
        E.NOMBRE_ESTADO AS ESTADO_SEGUIMIENTO
FROM FIDE_SEGUIMIENTO_TB SEG
JOIN FIDE_TIPO_SEGUIMIENTO TS ON SEG.ID_TIPO_SEGUIMIENTO = TS.ID_TIPO_SEGUIMIENTO
JOIN FIDE_ADOPCION_TB ADOP ON SEG.ID_ADOPCION = ADOP.ID_ADOPCION
JOIN FIDE_USUARIO_TB U ON ADOP.IDENTIFICACION = U.IDENTIFICACION
JOIN FIDE_ESTADO_TB E ON SEG.ID_ESTADO = E.ID_ESTADO;

/*

       6. HISTORIAL DE GASTOS CLINICOS

*/
CREATE OR REPLACE VIEW FIDE_GASTOS_CLINICOS_V AS
SELECT  EP.ID_EVENTO,
        P.ID_PERRITO,
        P.NOMBRE AS NOMBRE_PERRITO,
        TE.NOMBRE AS TIPO_EVENTO,
        EP.FECHA_EVENTO,
        EP.DETALLE,
        EP.TOTAL_GASTO
FROM FIDE_EVENTO_PERRITO_TB EP
JOIN FIDE_PERRITO_TB P ON EP.ID_PERRITO = P.ID_PERRITO
JOIN FIDE_TIPO_EVENTO_TB TE ON EP.ID_TIPO_EVENTO = TE.ID_TIPO_EVENTO
WHERE EP.ID_ESTADO = 1;

/*

       7. HISTORIAL DE DONACIONES

*/
CREATE OR REPLACE VIEW FIDE_HISTORIAL_DONACIONES_V AS
SELECT  D.ID_DONACION,
        D.FECHA_DONACION,
        U.NOMBRE || ' ' || U.APELLIDO_PATERNO AS DONADOR,
        C.NOMBRE AS CAMPANIA_DESTINO,
        D.MONTO,
        D.MENSAJE
FROM FIDE_DONACION_TB D
JOIN FIDE_USUARIO_TB U ON D.IDENTIFICACION = U.IDENTIFICACION
LEFT JOIN FIDE_CAMPANIA_TB C ON D.ID_CAMPANIA = C.ID_CAMPANIA
WHERE D.ID_ESTADO = 1;

/*

       8. DIRECTORIO DE CASAS CUNA

*/
CREATE OR REPLACE VIEW FIDE_DIRECTORIO_CASAS_CUNA_V AS
SELECT  CC.ID_CASA_CUNA,
        CC.NOMBRE AS NOMBRE_CASA,
        U.NOMBRE || ' ' || U.APELLIDO_PATERNO AS ENCARGADO,
        U.IDENTIFICACION AS ID_ENCARGADO,
        DIS.NOMBRE || ', ' || CAN.NOMBRE AS UBICACION,
        (SELECT COUNT(*) FROM FIDE_CASA_PERRITO_TB CP WHERE CP.ID_CASA_CUNA = CC.ID_CASA_CUNA AND CP.ID_ESTADO = 1) AS CANTIDAD_PERRITOS
FROM FIDE_CASA_CUNA_TB CC
JOIN FIDE_USUARIO_TB U ON CC.IDENTIFICACION = U.IDENTIFICACION
JOIN FIDE_DIRECCION_TB DIR ON CC.ID_DIRECCION = DIR.ID_DIRECCION
JOIN FIDE_DISTRITO_TB DIS ON DIR.ID_DISTRITO = DIS.ID_DISTRITO
JOIN FIDE_CANTON_TB CAN ON DIS.ID_CANTON = CAN.ID_CANTON
WHERE CC.ID_ESTADO = 1;

/*

       9. REGISTRO DE AUDITORIA PARA EL ADMIN

*/
CREATE MATERIALIZED VIEW FIDE_AUDITORIA_ADMIN_V AS
SELECT  A.ID_AUDITORIA,
        A.FECHA,
        U.NOMBRE || ' ' || U.APELLIDO_PATERNO AS USUARIO_RESPONSABLE,
        A.ACCION,
        A.ENTIDAD AS TABLA_AFECTADA,
        A.DETALLE
FROM FIDE_AUDITORIA_TB A
LEFT JOIN FIDE_USUARIO_TB U ON A.IDENTIFICACION = U.IDENTIFICACION
ORDER BY A.FECHA DESC;

/*

       10. REPORTE FINANCIERO MENSUAL

*/
CREATE MATERIALIZED VIEW FIDE_REPORTE_FINANCIERO_VM
BUILD IMMEDIATE REFRESH COMPLETE ON DEMAND AS
SELECT  TO_CHAR(FECHA_DONACION, 'YYYY-MM') AS MES_ANIO,
        'INGRESO_DONACION' AS TIPO_MOVIMIENTO,
        SUM(MONTO) AS TOTAL
FROM FIDE_DONACION_TB
WHERE ID_ESTADO = 1
GROUP BY TO_CHAR(FECHA_DONACION, 'YYYY-MM')
UNION ALL
SELECT  TO_CHAR(FECHA_VENTA, 'YYYY-MM') AS MES_ANIO,
        'INGRESO_VENTAS' AS TIPO_MOVIMIENTO,
        SUM(TOTAL_VENTA) AS TOTAL
FROM FIDE_VENTA_TB
WHERE ID_ESTADO = 1
GROUP BY TO_CHAR(FECHA_VENTA, 'YYYY-MM')
UNION ALL
SELECT  TO_CHAR(FECHA_EVENTO, 'YYYY-MM') AS MES_ANIO,
        'EGRESO_CLINICO' AS TIPO_MOVIMIENTO,
        SUM(TOTAL_GASTO) AS TOTAL
FROM FIDE_EVENTO_PERRITO_TB
WHERE ID_ESTADO = 1
GROUP BY TO_CHAR(FECHA_EVENTO, 'YYYY-MM');

/*

       11. METRICAS DE ADOPCION Y RESCATES

*/
CREATE MATERIALIZED VIEW FIDE_METRICAS_ADOPCION_VM 
BUILD IMMEDIATE REFRESH COMPLETE ON DEMAND AS
SELECT  R.NOMBRE AS RAZA,
        TO_CHAR(A.FECHA_ADOPCION, 'YYYY') AS ANIO,
        COUNT(A.ID_ADOPCION) AS TOTAL_ADOPCIONES
FROM FIDE_ADOPCION_TB A
JOIN FIDE_SOLICITUD_TB S ON A.ID_SOLICITUD = S.ID_SOLICITUD
JOIN FIDE_PERRITO_TB P ON S.ID_PERRITO = P.ID_PERRITO
JOIN FIDE_RAZA_TB R ON P.ID_RAZA = R.ID_RAZA
WHERE A.ID_ESTADO = 1
GROUP BY R.NOMBRE, TO_CHAR(A.FECHA_ADOPCION, 'YYYY');

/*

       12. CIERRE DE MOVIMIENTOS DE INVENTARIO

*/
CREATE MATERIALIZED VIEW FIDE_CIERRE_MOVIMIENTOS_INVENTARIO_VM
BUILD IMMEDIATE REFRESH COMPLETE ON DEMAND AS
SELECT  P.ID_PRODUCTO,
        P.NOMBRE AS PRODUCTO,
        TM.NOMBRE AS TIPO_MOVIMIENTO,
        TO_CHAR(MI.FECHA_MOVIMIENTO, 'YYYY-MM') AS MES,
        SUM(MI.CANTIDAD) AS TOTAL_ARTICULOS
FROM FIDE_MOVIMIENTO_INVENTARIO_TB MI
JOIN FIDE_PRODUCTO_TB P ON MI.ID_PRODUCTO = P.ID_PRODUCTO
JOIN FIDE_TIPO_MOVIMIENTO_TB TM ON MI.ID_TIPO_MOVIMIENTO = TM.ID_TIPO_MOVIMIENTO
WHERE MI.ID_ESTADO = 1
GROUP BY P.ID_PRODUCTO, P.NOMBRE, TM.NOMBRE, TO_CHAR(MI.FECHA_MOVIMIENTO, 'YYYY-MM');

